repos:
  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: bun x biome check --write .
        language: system
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false
        args: ["apps/web/src"]
